In [1]:
import numpy as np
import math
import pandas as pd

In [22]:
train=pd.read_csv('matrix.csv').to_numpy()
df_1=pd.read_csv('matrix.csv')
test=pd.read_csv('matrix2.csv').to_numpy()
df=pd.read_csv('matrix2.csv')
df

Unnamed: 0     x      x^2         x^3          x^4
0           1  5.84  34.1056  199.176704  1163.191951
1           1  0.61   0.3721    0.226981     0.138458
2           1  4.23  17.8929   75.686967   320.155870
3           1  6.50  42.2500  274.625000  1785.062500
4           1  0.89   0.7921    0.704969     0.627422
5           1  3.75  14.0625   52.734375   197.753906
6           1  5.73  32.8329  188.132517  1077.999322
7           1  3.10   9.6100   29.791000    92.352100
8           1  6.47  41.8609  270.840023  1752.334949
9           1  4.59  21.0681   96.702579   443.864838

In [3]:
train.shape
test.shape

(10, 5)

In [4]:
def norm(x):
    ans=0
    for i in x:
            ans+=math.pow(i,2)
    return ans

In [35]:
def cal(x,y,para):
    return norm(x.T.dot(para)-y)

In [6]:
y_test=np.array([0.89,1.79,-0.15,1.63,1.27,0.91,0.88,1.41,1.69,-0.46])
y_train=np.array([0.81,1.22,0.43,-0.51,-0.13,0.44,1.49,0.31,1.59,1.61])

In [26]:
para_4=[-1.90765685,4.81138824,-2.29185417,0.38599269,-0.02100545]
para_2=[2.28532665,-1.0375317,0.12251943]
para_1=[-0.08930311,0.15199536]

In [36]:
total=0
for i in test:
    total+=cal(i,y_test,para_4)
total

96.91043659216291

In [20]:

x_2=df[[df.columns[0],df.columns[1],df.columns[2]]].to_numpy()
x_2

array([[ 1.    ,  5.84  , 34.1056],
       [ 1.    ,  0.61  ,  0.3721],
       [ 1.    ,  4.23  , 17.8929],
       [ 1.    ,  6.5   , 42.25  ],
       [ 1.    ,  0.89  ,  0.7921],
       [ 1.    ,  3.75  , 14.0625],
       [ 1.    ,  5.73  , 32.8329],
       [ 1.    ,  3.1   ,  9.61  ],
       [ 1.    ,  6.47  , 41.8609],
       [ 1.    ,  4.59  , 21.0681]])

In [21]:
total=0
for i in x_2:
    total+=cal(i,y_test,para_2)
total

97.18230054820535

In [25]:
temp=df_1[[df_1.columns[0],df_1.columns[1]]]
np.linalg.inv(temp.T.dot(temp)).dot(temp.T.dot(y_train))

array([-0.08930311,  0.15199536])

In [27]:
x_1=df[[df.columns[0],df.columns[1]]].to_numpy()
x_1

array([[1.  , 5.84],
       [1.  , 0.61],
       [1.  , 4.23],
       [1.  , 6.5 ],
       [1.  , 0.89],
       [1.  , 3.75],
       [1.  , 5.73],
       [1.  , 3.1 ],
       [1.  , 6.47],
       [1.  , 4.59]])

In [28]:
total=0
for i in x_1:
    total+=cal(i,y_test,para_1)
total

81.16876962038941

In [37]:
temp=df_1[[df_1.columns[0],df_1.columns[1],df_1.columns[2]]]
np.linalg.inv(temp.T.dot(temp)).dot(temp.T).dot(y_train)

array([ 2.28532665, -1.0375317 ,  0.12251943])

In [32]:
para_ridge=np.array([ 0.99543042,  0.76255503, -0.6770271 ,  0.13763658, -0.00796322])
para_ridge

array([ 0.99543042,  0.76255503, -0.6770271 ,  0.13763658, -0.00796322])

In [33]:
test


array([[1.00000000e+00, 5.84000000e+00, 3.41056000e+01, 1.99176704e+02,
        1.16319195e+03],
       [1.00000000e+00, 6.10000000e-01, 3.72100000e-01, 2.26981000e-01,
        1.38458410e-01],
       [1.00000000e+00, 4.23000000e+00, 1.78929000e+01, 7.56869670e+01,
        3.20155870e+02],
       [1.00000000e+00, 6.50000000e+00, 4.22500000e+01, 2.74625000e+02,
        1.78506250e+03],
       [1.00000000e+00, 8.90000000e-01, 7.92100000e-01, 7.04969000e-01,
        6.27422410e-01],
       [1.00000000e+00, 3.75000000e+00, 1.40625000e+01, 5.27343750e+01,
        1.97753906e+02],
       [1.00000000e+00, 5.73000000e+00, 3.28329000e+01, 1.88132517e+02,
        1.07799932e+03],
       [1.00000000e+00, 3.10000000e+00, 9.61000000e+00, 2.97910000e+01,
        9.23521000e+01],
       [1.00000000e+00, 6.47000000e+00, 4.18609000e+01, 2.70840023e+02,
        1.75233495e+03],
       [1.00000000e+00, 4.59000000e+00, 2.10681000e+01, 9.67025790e+01,
        4.43864838e+02]])

In [34]:
total=0
for i in test:
    total+=cal(i,y_test,para_ridge)

total+=0.1*norm(para_ridge)
total

94.04093327514629

In [38]:
test_plot=df[df.columns[1]]
test_plot

0    5.84
1    0.61
2    4.23
3    6.50
4    0.89
5    3.75
6    5.73
7    3.10
8    6.47
9    4.59
Name: x, dtype: float64

In [39]:
import matplotlib.pyplot as plt 


In [40]:
train


array([[1.00000000e+00, 5.51000000e+00, 3.03601000e+01, 1.67284151e+02,
        9.21735672e+02],
       [1.00000000e+00, 1.25000000e+00, 1.56250000e+00, 1.95312500e+00,
        2.44140625e+00],
       [1.00000000e+00, 3.60000000e+00, 1.29600000e+01, 4.66560000e+01,
        1.67961600e+02],
       [1.00000000e+00, 4.72000000e+00, 2.22784000e+01, 1.05154048e+02,
        4.96327107e+02],
       [1.00000000e+00, 3.91000000e+00, 1.52881000e+01, 5.97764710e+01,
        2.33726002e+02],
       [1.00000000e+00, 6.13000000e+00, 3.75769000e+01, 2.30346397e+02,
        1.41202341e+03],
       [1.00000000e+00, 8.05000000e+00, 6.48025000e+01, 5.21660125e+02,
        4.19936401e+03],
       [1.00000000e+00, 5.55000000e+00, 3.08025000e+01, 1.70953875e+02,
        9.48794006e+02],
       [1.00000000e+00, 7.33000000e+00, 5.37289000e+01, 3.93832837e+02,
        2.88679470e+03],
       [1.00000000e+00, 7.59000000e+00, 5.76081000e+01, 4.37245479e+02,
        3.31869319e+03]])

In [41]:
para_4

[-1.90765685, 4.81138824, -2.29185417, 0.38599269, -0.02100545]

In [42]:
total=0
for i in train:
    total+=cal(i,y_train,para_4)
total

92.58117287096593